### ISSUE TITLE
a menu bug

### ISSUE THREAD

**Issue by sjmjulia** [ShiWeiCN/Berry#1]
<img width="378" alt="screen shot 2017-04-21 at 11 14 53 pm" src="https://cloud.githubusercontent.com/assets/5000788/25284344/4d2bbccc-26e9-11e7-990e-a617ebf869c0.png">
there is a gap bewteen the navigation bar and the menu ... i wonder where there is a problem?

**Comment by devswi** [comment]
That was so strange, I fixed this problem at version **0.1.3**, could you please confirm the version you used.

**Comment by sjmjulia** [comment]
ok， it is resolved
